name: surf_flutter_ci_cd
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  # path: ^1.8.0
  args: ^2.3.1
  process_run: any
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
